# Generated by Django 4.2.8 on 2023-12-06 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_historicalsocialhistorydata_medical_drugs_history_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classificationofdiseases",
            unique_together={("code", "parent")},
        ),
    ]
