version: '3.8'

services:

  limesurvey_db:
    image: postgres:11-alpine
    volumes:
      - limesurvey_pgdata:/var/lib/postgresql/data:delegated
    restart: unless-stopped
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: limesurvey_db
      POSTGRES_USER: ${LIMESURVEY_DB_USERNAME:-limesurvey_user}
      POSTGRES_PASSWORD: ${LIMESURVEY_DB_PASSWORD:-lime_password}

  limesurvey:
    image: neuromat/nes-compose:limesurvey
    volumes:
      - "limesurvey_data:/var/www/limesurvey"
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      LIMESURVEY_PORT: 8080
      LIMESURVEY_DB_TYPE: pgsql
      LIMESURVEY_DB_HOST: limesurvey_db
      LIMESURVEY_DB_PORT: 5432
      LIMESURVEY_DB_NAME: limesurvey_db
      LIMESURVEY_DB_TABLE_PREFIX: lime_
      LIMESURVEY_DB_USERNAME: ${LIMESURVEY_DB_USERNAME:-limesurvey_user}
      LIMESURVEY_DB_PASSWORD: ${LIMESURVEY_DB_PASSWORD:-lime_password}
      LIMESURVEY_ADMIN_USER: ${LIMESURVEY_ADMIN_USER:-lime_admin}
      LIMESURVEY_ADMIN_PASSWORD: ${LIMESURVEY_ADMIN_PASSWORD:-lime_admin_password}
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: limesurvey@limemail.fake
      LIMESURVEY_URL_FORMAT: path
      #LIMESURVEY_URL_DOWNLOAD: https://github.com/LimeSurvey/LimeSurvey/archive/5.6.32+230731.tar.gz
    depends_on:
      - limesurvey_db

  nes_db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - nes_pgdata:/var/lib/postgresql/data:delegated
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: nes_db
      POSTGRES_USER: ${NES_DB_USER:-nes_user}
      POSTGRES_PASSWORD: ${NES_DB_PASSWORD:-nes_password}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5

  nes:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        DEBUG: 0
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      NES_DIR: /usr/local/nes
      NES_DB_TYPE: pgsql
      NES_DB_HOST: nes_db
      NES_DB: nes_db
      NES_DB_USER: ${NES_DB_USER:-nes_user}
      NES_DB_PASSWORD: ${NES_DB_PASSWORD:-nes_password}
      NES_DB_PORT: 5432
      NES_SECRET_KEY: ${NES_SECRET_KEY:-your_secret_key}
      NES_HOSTNAME: lapisnes.local
      NES_IP: 0.0.0.0
      NES_PORT: 80
      NES_ADMIN_USER: ${NES_ADMIN_USER:-nes_admin}
      NES_ADMIN_EMAIL: ${NES_ADMIN_EMAIL:-nes_admin@nesmail.com}
      NES_ADMIN_PASSWORD: ${NES_ADMIN_PASSWORD:-nes_admin_password}
      LIMESURVEY_ADMIN_USER: ${LIMESURVEY_ADMIN_USER:-lime_admin}
      LIMESURVEY_ADMIN_PASSWORD: ${LIMESURVEY_ADMIN_PASSWORD:-lime_admin_password}
      LIMESURVEY_HOST: limesurvey
      LIMESURVEY_PORT: 8080
    volumes:
      - nes_data:/usr/local/nes
    depends_on:
      - nes_db
      - limesurvey

volumes:
  nes_data: 
  nes_pgdata:
  limesurvey_pgdata:
  limesurvey_data:
