version: '3.8'

services:
  jupyterhub:
    container_name: jupyterhub.nes
    hostname: jupyterhub
    build: https://github.com/mcostat/nes-jupyterhub.git
    image: nes-jupyterhub
    restart: unless-stopped
    volumes:
      - nes_media:/nes/media:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - jupyterhub_data:/data
    networks:
      - nes_network
      - jupyterhub_network
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      DOCKER_NETWORK_NAME: jupyterhub_network
    depends_on:
      - nes_dev

  limesurvey_db:
    extends:
      file: ../docker/docker-compose.yml
      service: limesurvey_db
    env_file:
      - .env

  limesurvey:
    extends:
      file: ../docker/docker-compose.yml
      service: limesurvey
    env_file:
      - .env
    depends_on:
      - limesurvey_db

  nes_db:
    extends:
      file: ../docker/docker-compose.yml
      service: nes_db
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5

  nes_dev:
    extends:
      file: ../docker/docker-compose.yml
      service: nes
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    stdin_open: true
    tty: true
    ports:
      - 80:80
    volumes:
      - ../..:/workspaces:cached
      - nes_media:/workspaces/nes/patientregistrationsystem/qdc/media:rw
    env_file:
      - .env
    environment:
      DEBUG: true
      DJANGO_SETTINGS_MODULE: qdc.settings.dev
      NES_DIR: /workspaces/nes
      NES_HOSTNAME: localhost
      LIMESURVEY_URL_WEB: localhost
    depends_on:
      - nes_db
      - limesurvey

volumes:
  limesurvey_pgdata:
  limesurvey_data:
  nes_pgdata:
  nes_media:
  jupyterhub_data:
  nes_data:


networks:
  nes_network:
    name: nes_network
  jupyterhub_network:
    name: jupyterhub_network
