version: '3.8'

services:
  #TODO: Separete nes and limesurvey
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    environment:
      NES_DB_TYPE: pgsql
      NES_DB_HOST: db
      NES_DB: nes_db
      NES_DB_USER: nes_user
      NES_DB_PASSWORD: nes_password
      NES_DB_PORT: 5432
      NES_SECRET_KEY: _my_very_secret_key_
      NES_IP: 0.0.0.0
      NES_PORT: 8000
      NES_ADMIN_USER: nes_admin
      NES_ADMIN_EMAIL: nes_admin@nesmail.com
      NES_ADMIN_PASSWORD: nes_admin_password
      LIMESURVEY_HOST: localhost
      LIMESURVEY_PORT: 80
      LIMESURVEY_ADMIN_USER: limesurvey_admin
      LIMESURVEY_ADMIN_PASSWORD: limesurvey_admin_password
      
    depends_on:
      - db

  db:
    image: postgres:latest

    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB="${POSTGRES_DB:-nes_db}"
      - POSTGRES_USER="${POSTGRES_USER:-nes_user}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-nes_password}"
      - PGDATA="${PGDATA:-/var/lib/postgresql/data}"
      - POSTGRES_HOST_AUTH_METHOD="md5"
      - POSTGRES_INITDB_ARGS=--auth-host="md5"
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - "5432:5432"

volumes:
  postgres-data:
