# Generated by Django 4.2.7 on 2023-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="en_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="survey",
            name="pt_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
