# Generated by Django 4.2.7 on 2023-11-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_alter_survey_en_title_alter_survey_pt_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="en_title",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="pt_title",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
