# Generated by Django 4.2.7 on 2023-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0003_alter_survey_en_title_alter_survey_pt_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="en_title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="survey",
            name="pt_title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
