name: 'Dependency Review'
on:
    push:
      branches: ["actions"]
    pull_request:
      branches: ["actions"]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
            base-ref: master
            head-ref: actions