name: Quality Assurance

on:   
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
    quality-assurance:
        name: Quality Assurance
        runs-on: ubuntu-latest

        services:
            nes_db:
                image: postgres:16-bookworm
                env:
                    POSTGRES_DB: nes_db
                    POSTGRES_USER: nes_user
                    POSTGRES_PASSWORD: nes_password
                    PGDATA: /var/lib/postgresql/data
                    PGCLIENTENCODING: UTF8
                ports:
                  - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        defaults:
          run:
            shell: bash
            working-directory: patientregistrationsystem/qdc
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
              python-version: '3.11'
              cache: 'pip' # caching pip dependencies
          - name: Install requirements
            run: pip install -r requirements.txt  
          - name: Run Entrypoint
            working-directory: patientregistrationsystem/qdc
            run: prepare_server.sh
          - name: Run Tests
            run: |
              python3 manage.py test
