name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
    quality-assurance:
        name: Quality Assurance
        runs-on: ubuntu-latest
        container: python:3.11-slim-bookworm

    services:
        nes_db:
            container: postgres:16-bookworm
            env:
                POSTGRES_DB: nes_db
                POSTGRES_USER: user
                POSTGRES_PASSWORD: pass
                PGDATA: /var/lib/postgresql/data
                PGCLIENTENCODING: UTF8

    steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.11
          uses: actions/setup-python@v3
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run Tests
          run: |
            python3 manage.py test
