name: Quality Assurance

on:   
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
    quality-assurance:
        name: Quality Assurance
        runs-on: ubuntu-latest

        services:
            nes_db:
                image: postgres:16-bookworm
                env:
                    POSTGRES_DB: nes_db
                    POSTGRES_USER: nes_user
                    POSTGRES_PASSWORD: nes_password
                    PGDATA: /var/lib/postgresql/data
                    PGCLIENTENCODING: UTF8
                    POSTGRES_HOST_AUTH_METHOD: md5
                    POSTGRES_INITDB_ARGS: --auth-host=md5
                ports:
                  - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        defaults:
          run:
            shell: bash
            working-directory: ./patientregistrationsystem/qdc
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
              python-version: '3.11'
              cache: 'pip'
          - name: Install requirements
            run: |
              pip install flake8 |
              pip install -r requirements.txt  
          - name: Run NES setup
            run: |
              sh prepare_server.sh
          - name: Python Linter
            run: flake8 .
          - name: Run Tests
            run: |
              python3 -u manage.py test
