name: Quality Assurance

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  DJANGO_SETTINGS_MODULE: qdc.settings.test
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest

    services:
      limesurvey_db:
        image: postgres:11-bookworm
        env:
          POSTGRES_DB: limesurvey_db
          POSTGRES_USER: limesurvey_user
          POSTGRES_PASSWORD: lime_password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      limesurvey:
        image: neuromat/nes-compose:limesurvey
        ports:
          - "8080:8080"
        env:
          LIMESURVEY_PORT: 8080
          LIMESURVEY_DB_TYPE: pgsql
          LIMESURVEY_DB_HOST: limesurvey_db
          LIMESURVEY_DB_PORT: 5432
          LIMESURVEY_DB_NAME: limesurvey_db
          LIMESURVEY_DB_TABLE_PREFIX: lime_
          LIMESURVEY_DB_USERNAME: limesurvey_user
          LIMESURVEY_DB_PASSWORD: lime_password
          LIMESURVEY_ADMIN_USER: lime_admin
          LIMESURVEY_ADMIN_PASSWORD: lime_admin_password
          LIMESURVEY_ADMIN_NAME: Lime Administrator
          LIMESURVEY_ADMIN_EMAIL: limesurvey@limemail.fake
          LIMESURVEY_URL_FORMAT: path

      nes_db:
        image: postgres:16-bookworm
        env:
          POSTGRES_DB: nes_db
          POSTGRES_USER: nes_user
          POSTGRES_PASSWORD: nes_password
          PGDATA: /var/lib/postgresql/data
          PGCLIENTENCODING: UTF8
          POSTGRES_HOST_AUTH_METHOD: md5
          POSTGRES_INITDB_ARGS: --auth-host=md5
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    defaults:
      run:
        shell: bash
        working-directory: ./patientregistrationsystem/qdc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: "2"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NES setup
        run: |
          sh setup_nes_test.sh

      - name: Check Djando deploy
        run: |
          python -u manage.py check --deploy
      - name: Run Tests
        run: |
          coverage run --omit=*/tests/*,*/migrations/* manage.py test && coverage report --fail-under=60 && coverage xml
      - name: Check formating
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "patientregistrationsystem/qdc/"
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
        continue-on-error: true
      # - run: mypy $(git ls-files '*.py')
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3

