# Generated by Django 4.2.7 on 2023-11-15 15:19

from django.db import migrations, models

import configuration.models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0004_usefullink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localinstitution",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=configuration.models.get_institution_logo_dir),
        ),
    ]
